### ISSUE TITLE
Running this on CLI but output redirect me to browser ?

### ISSUE THREAD

**Issue by navotera** [i-love-cats1/Google-Drive-sync#3]
Hi im running this on CLI but output of upload.py redirect me to some google page... since i run in localhost this wont work ... 

is there somekind of method to enable this without using the browser authentication ? 

thank u

**Comment by AnderUstarroz** [comment]
you can run it from console using the flag **--noauth_local_webserver**
`python3 upload_to_drive.py --noauth_local_webserver`

The first time you run this command you will need to copy the link displayed on screen  and paste it on 
 your own browser to accept the access. This will store the credentials for future executions at **/root/.credentials/drive-python-sync.json**

**Comment by navotera** [comment]
i forget when i using this library ...  ;)

i closing this instead... thanks
